/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodavelha;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alisson
 */
public class Janela_J_V extends javax.swing.JFrame {
    
    public int contador;
    public int[][] matriz = new int[3][3];
    
    /**
     * Creates new form Janela_J_V
     */
    public Janela_J_V() {
        initComponents();
        contador = 0;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                matriz[i][j] = -1;
            }
        }
        bt00.setBackground(Color.LIGHT_GRAY);
        bt01.setBackground(Color.LIGHT_GRAY);
        bt02.setBackground(Color.LIGHT_GRAY);
        bt10.setBackground(Color.LIGHT_GRAY);
        bt11.setBackground(Color.LIGHT_GRAY);
        bt12.setBackground(Color.LIGHT_GRAY);
        bt20.setBackground(Color.LIGHT_GRAY);
        bt21.setBackground(Color.LIGHT_GRAY);
        bt22.setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bt01 = new javax.swing.JButton();
        bt00 = new javax.swing.JButton();
        bt02 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt20 = new javax.swing.JButton();
        bt21 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt22 = new javax.swing.JButton();
        jbJogar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton9.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        bt01.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt01ActionPerformed(evt);
            }
        });

        bt00.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt00ActionPerformed(evt);
            }
        });

        bt02.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt02ActionPerformed(evt);
            }
        });

        bt10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });

        bt12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });

        bt20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt20ActionPerformed(evt);
            }
        });

        bt21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt21ActionPerformed(evt);
            }
        });

        bt11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });

        bt22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt00, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt01, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt02, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt01, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt02, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbJogar.setText("Joga");
        jbJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJogarActionPerformed(evt);
            }
        });

        jButton1.setText("Restart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbJogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(77, 77, 77)
                        .addComponent(jbJogar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt00ActionPerformed
        
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt00.setText("X");
            matriz[0][0] = 1;
        } else {
            bt00.setText("O");
            matriz[0][0] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt00.setEnabled(false);
    }//GEN-LAST:event_bt00ActionPerformed

    private void bt01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt01ActionPerformed
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt01.setText("X");
            matriz[0][1] = 1;
        } else {
            bt01.setText("O");
            matriz[0][1] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt01.setEnabled(false);
    }//GEN-LAST:event_bt01ActionPerformed

    private void bt02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt02ActionPerformed
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt02.setText("X");
            matriz[0][2] = 1;
        } else {
            bt02.setText("O");
            matriz[0][2] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt02.setEnabled(false);
    }//GEN-LAST:event_bt02ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt10.setText("X");
            matriz[1][0] = 1;
        } else {
            bt10.setText("O");
            matriz[1][0] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt10.setEnabled(false);
    }//GEN-LAST:event_bt10ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt11.setText("X");
            matriz[1][1] = 1;
        } else {
            bt11.setText("O");
            matriz[1][1] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt11.setEnabled(false);
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt12.setText("X");
            matriz[1][2] = 1;
        } else {
            bt12.setText("O");
            matriz[1][2] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt12.setEnabled(false);
    }//GEN-LAST:event_bt12ActionPerformed

    private void bt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt20ActionPerformed
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt20.setText("X");
            matriz[2][0] = 1;
        } else {
            bt20.setText("O");
            matriz[2][0] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt20.setEnabled(false);
    }//GEN-LAST:event_bt20ActionPerformed

    private void bt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt21ActionPerformed
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt21.setText("X");
            matriz[2][1] = 1;
        } else {
            bt21.setText("O");
            matriz[2][1] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt21.setEnabled(false);
    }//GEN-LAST:event_bt21ActionPerformed

    private void bt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt22ActionPerformed
        System.out.println("Contador = "+contador);
        if ( contador%2==0 ) 
        {
            bt22.setText("X");
            matriz[2][2] = 1;
        } else {
            bt22.setText("O");
            matriz[2][2] = 0;
        }
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        if (contador%2==0){
            jbJogar.setEnabled(false);
        } else {
            jbJogar.setEnabled(true);
        }
        contador++;
        bt22.setEnabled(false);
    }//GEN-LAST:event_bt22ActionPerformed
    
    void testeSeVenceuEmpatouPerdeu(int[][] matriz, int status){
        boolean flag = true;
        for (int i = 0 ; i < 3; i++){
            flag = true;
            for (int j = 0; j < 3; j++) {
                if ( matriz[i][j] == status ){
                    
                } else {
                    flag = false;
                    j = 3;
                }
                
            }
            if (flag){
                    JOptionPane.showMessageDialog(rootPane,"Você VENCEU, parabéns!!!", "VENCEDOR", HEIGHT);
                    if (i==0){
                        bt00.setBackground(Color.red);
                        bt01.setBackground(Color.red);
                        bt02.setBackground(Color.red);
                    }
                    if (i==1){
                        bt10.setBackground(Color.red);
                        bt11.setBackground(Color.red);
                        bt12.setBackground(Color.red);
                    }
                    if (i==2){
                        bt20.setBackground(Color.red);
                        bt21.setBackground(Color.red);
                        bt22.setBackground(Color.red);
                    }
                return;
            }
        }
        
        for (int i = 0 ; i < 3; i++){
            flag = true;
            for (int j = 0; j < 3; j++) {
                if ( matriz[j][i] == status ){
                    
                } else {
                    flag = false;
                    j = 3;
                }
                
            }
            if (flag){
                    JOptionPane.showMessageDialog(rootPane,"Você VENCEU, parabéns!!!", "VENCEDOR", HEIGHT);
                    if (i==0){
                        bt00.setBackground(Color.red);
                        bt10.setBackground(Color.red);
                        bt20.setBackground(Color.red);
                    }
                    if (i==1){
                        bt01.setBackground(Color.red);
                        bt11.setBackground(Color.red);
                        bt21.setBackground(Color.red);
                    }
                    if (i==2){
                        bt02.setBackground(Color.red);
                        bt12.setBackground(Color.red);
                        bt22.setBackground(Color.red);
                    }
                return;
            }
        }
        flag = true;
        for (int i = 0; i<3; i++){
             if ( matriz[i][i] == status ){
                    
                } else {
                    flag = false;
                    i = 3;
                }
        }
        if (flag){
            JOptionPane.showMessageDialog(rootPane,"Você VENCEU, parabéns!!!", "VENCEDOR", HEIGHT);
            bt00.setBackground(Color.red);
            bt11.setBackground(Color.red);
            bt22.setBackground(Color.red);
            return; 
        }
        flag = true;
        for (int i = 0, j = 2; i<3; i++, j--){
             if ( matriz[i][j] == status ){
                    
                } else {
                    flag = false;
                    i = 3;
                }
        }
        if (flag){
            JOptionPane.showMessageDialog(rootPane,"Você VENCEU, parabéns!!!", "VENCEDOR", HEIGHT);
            bt02.setBackground(Color.red);
            bt11.setBackground(Color.red);
            bt20.setBackground(Color.red);
            return; 
        }
        
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if ( matriz[i][j] == -1){
                    return;
                }
            }
        }
        
        JOptionPane.showMessageDialog(this, "Empate!!!", "EMPATE", 0);
    }
    
    private void jbJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJogarActionPerformed
        
        Estado estado = new Estado(matriz);
        
        int[][] respostaMatriz = new int[3][3];
        System.out.println("Contador = "+contador);
        
        estado.status = contador%2 == 0 ? 1 : 0;
        estado.controle = estado.status;
        System.out.println("Stado status = "+estado.status);

        respostaMatriz = JogoDaVelha.minMax(estado);
        
        matriz = respostaMatriz;
        if ( matriz[0][0] == 0){
            bt00.setText("O");
            bt00.setEnabled(false);
        }
        else if (matriz[0][0] == 1)
        {
            bt00.setText("X");
            bt00.setEnabled(false);
        }
        else
            bt00.setText("");
            
        if ( matriz[0][1] == 0)
        {
            bt01.setText("O");
            bt01.setEnabled(false);
        }
        else if (matriz[0][1] == 1)
        {
            bt01.setText("X");
            bt01.setEnabled(false);
        }else
            bt01.setText("");
        
        if ( matriz[0][2] == 0)
        {
            bt02.setText("O");
            bt02.setEnabled(false);
        }
        else if (matriz[0][2] == 1)
        {
            bt02.setText("X");
            bt02.setEnabled(false);
        }else
            bt02.setText("");
        
        if ( matriz[1][0] == 0)
        {
            bt10.setText("O");
            bt10.setEnabled(false);
        }
        else if (matriz[1][0] == 1)
        {
            bt10.setText("X");
            bt10.setEnabled(false);
        }else
            bt10.setText("");
        
        if ( matriz[1][1] == 0)
        {
            bt11.setText("O");
            bt11.setEnabled(false);
        }
        else if (matriz[1][1] == 1)
        {
            bt11.setText("X");
            bt11.setEnabled(false);
        }else
            bt11.setText("");
        
        if ( matriz[1][2] == 0)
        {
            bt12.setText("O");
            bt12.setEnabled(false);
        }
        else if (matriz[1][2] == 1)
        {
            bt12.setText("X");
            bt12.setEnabled(false);
        }else
            bt12.setText("");
        
        if ( matriz[2][0] == 0)
        {
            bt20.setText("O");
            bt20.setEnabled(false);
        }
        else if (matriz[2][0] == 1)
        {
            bt20.setText("X");
            bt20.setEnabled(false);
        }else
            bt20.setText("");
        
        if ( matriz[2][1] == 0)
        {
            bt21.setText("O");
            bt21.setEnabled(false);
        }
        else if (matriz[2][1] == 1)
        {
            bt21.setText("X");
            bt21.setEnabled(false);
        }else
            bt21.setText("");
        
        if ( matriz[2][2] == 0)
        {
            bt22.setText("O");
            bt22.setEnabled(false);
        }
        else if (matriz[2][2] == 1)
        {
            bt22.setText("X");
            bt22.setEnabled(false);
        }else
            bt22.setText("");
        
        System.out.println("Contador = "+contador);
        
        
        System.out.println("Fim bt start");
        
        testeSeVenceuEmpatouPerdeu(matriz, contador%2==0 ? 1:0);
        contador++;
        
        jbJogar.setEnabled(false);
        
    }//GEN-LAST:event_jbJogarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        contador = 0;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                matriz[i][j] = -1;
            }
        }
        bt00.setBackground(Color.LIGHT_GRAY);
        bt01.setBackground(Color.LIGHT_GRAY);
        bt02.setBackground(Color.LIGHT_GRAY);
        bt10.setBackground(Color.LIGHT_GRAY);
        bt11.setBackground(Color.LIGHT_GRAY);
        bt12.setBackground(Color.LIGHT_GRAY);
        bt20.setBackground(Color.LIGHT_GRAY);
        bt21.setBackground(Color.LIGHT_GRAY);
        bt22.setBackground(Color.LIGHT_GRAY);
        bt00.setText("");
        bt01.setText("");
        bt02.setText("");
        bt10.setText("");
        bt11.setText("");
        bt12.setText("");
        bt20.setText("");
        bt21.setText("");
        bt22.setText("");
        bt00.setEnabled(true);
        bt01.setEnabled(true);
        bt02.setEnabled(true);
        bt10.setEnabled(true);
        bt11.setEnabled(true);
        bt12.setEnabled(true);
        bt20.setEnabled(true);
        bt21.setEnabled(true);
        bt22.setEnabled(true);
        jbJogar.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_J_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_J_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_J_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_J_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela_J_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt00;
    private javax.swing.JButton bt01;
    private javax.swing.JButton bt02;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt20;
    private javax.swing.JButton bt21;
    private javax.swing.JButton bt22;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbJogar;
    // End of variables declaration//GEN-END:variables
}
